[tool.poetry]
name = "llama-toolbox"
version = "0.1.0"
description = "A collection of tools for LLaMA 3.x LLMs"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
json = "^0.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"